

'''
List Comprehension
List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list.

Example:
Based on a list of fruits, you want a new list, containing only the fruits with the letter "a" in the name.
Without list comprehension you will have to write a for statement with a conditional test inside'''


'''
#  Syntax
[expression for item in iterable if condition = True]

#  Parameters:
expression: operation or value to include in the new list.
item: current element from the iterable.
iterable: sequence like a list, tuple or range.
if condition (optional): filter to include only items that satisfy the condition.'''


# Example
fruits = ['apple', 'banana', 'mango', 'cheryy', 'lemon', 'melon']
newlist = []
for x in fruits:
    if 'a' in x:
        newlist.append(x)

print(newlist)

# newlist = [expression for item in iterable if condition == True]    syntax
# With list comprehension you can do all that with only one line of code:
fruits = ['apple', 'banana', 'mango', 'cheryy', 'lemon', 'melon']
newlist = [x for x in fruits if 'a' in x]
print(newlist)



#another example
fruits = ['apple', 'banana', 'mango', 'cheryy', 'lemon', 'melon']
newlist = [x for x in fruits if x != 'apple']
print(newlist)

'''
new_list = [expression    for item    in iterable]
              ↑              ↑            ↑
        what to store    variable     where values come from'''


# also you can use the range function to iterable
last = [x for x in range(10)]        
print(last)

# now add some codition on this loop
last = [x for x in range(10) if x < 5]
print(last)

# another square example
square = [x*x for x in range(10)]
print(square)


# you can use the function in expression to uppercase the item
fruits = ['apple', 'banana', 'mango', 'cheryy', 'lemon', 'melon']
newlist = [x.upper() for x in fruits if 'a' in x]
print(newlist)


# you can also set the 'string' in expression ;   Set all values in the new list to 'hello':
fruits = ['apple', 'banana', 'mango', 'cheryy', 'lemon', 'melon']
newlist = ['hello' for x in fruits]
print(newlist)



# he expression can also contain conditions, not like a filter, but as a way to manipulate the outcome:
# Return "orange" instead of "banana":
# new_list = [value_if_true if condition else value_if_false for item in iterable]     : syntax
fruits = ['apple', 'banana', 'mango', 'cheryy', 'lemon', 'melon']
newlist = [x if x != 'banana' else 'orange' for x in fruits]
print(newlist)

# this will be same as that 
fruits = ['apple', 'banana', 'mango', 'cheryy', 'lemon', 'melon']
newlist = []
for x in fruits:
   if x != 'banana':
       newlist.append(x)
   else:
       newlist.append('orange')

print(newlist)






# another number example
num = [1, 2, 3, 4, 5]
square = []
for value in num:
    result = value **2
    square.append(result)
print(square)

# Suppose you want to square every number in a list: list comprehension
num = [1, 2, 3, 4, 5]
square = [value ** 2 for value in num]
print(square)


# another example number
num = [1, 2, 3, 4, 6]
res = [x for x in num if x % 2 == 0]
print(res)

# complete code of this list comprehension
num = [1, 2, 3, 4, 6]
res = []
for x in num:
    if x % 2 == 0:
        res.append(x)

print(res)




# Using nested loops: A list of all coordinate pairs in a 3x3 grid can be generated by combining two loops inside a list comprehension.

all = [(x,y) for x in range(3) for y in range(3)]
print(all)
# full list code of this list comprehension
all = []
for x in range(3):
    for y in range(3):
        all.append((x,y))

print(all)
print(type(all))
print(type((x,y)))




